### ISSUE TITLE
Difference between concoct and viewbuilder

### ISSUE THREAD

**Issue by bitfl0wer** [concoct-rs/viewbuilder#1]
The libraries concoct and viewbuilder look much the same from the outside, and none of the two seem to depend on the other. What is the difference between them?

**Comment by bitfl0wer** [comment]
Also, from the perspective of someone who is looking to contribute: Which one of the two should I rather focus on? Is there any Roadmap available to somehow gauge what should be worked on (next)?

**Comment by matthunz** [comment]
I think a roadmap would be a great idea, I'll try to get one out ASAP. Basically the plan is to have Viewbuilder be a generic renderer for native GUIs and concoct as a frontend. I'm really hoping this crate can be used with multiple GUI frameworks and concoct can be used with multiple backends (like this and the web).

Right now the roadmap for the next release of Viewbuilder is:
1. Finish the Semantics and Layout trees
2. Create an element tree that uses the above trees
3. Reimplement rendering with skia

Also I recently changed direction and my current plan is to integrate with dioxus first to see if their react-style of UI is better. Definitely keeping concoct around as an option though so I'd love help with either.

**Comment by bitfl0wer** [comment]
Interesting! I definitely liked the Elm-inspired architecture of concoct and have made contact with this style of UI development through the Iced library in the past. However, I didn't end up using Iced, because it lacks accessibility support, which viewbuilder seems to have (<3 !!!). The HTML-like API of viewbuilder is really nice too, though! It definitely feels very intuitive and easy to use.

So, if I understand correctly, viewbuilder is supposed to be a GUI-Library, whereas concoct is supposed to be a frontend library?

By the way, if you'd like to connect on Discord/Matrix/etc., I'd be happy to do so! :)

**Comment by matthunz** [comment]
Glad ya like it! I had the same path, I feel like every rust UI framework is missing something so I just wanted to start from the ground up with what wasn't there.

I'd love to talk more on discord! My username is matthunz#2901
